# This file was generated by GoReleaser. DO NOT EDIT.
class Xterrafile < Formula
  desc "Systematically manage external modules from Github for use in Terraform."
  homepage "https://github.com/devopsmakers/xterrafile"
  url "https://github.com/devopsmakers/xterrafile/releases/download/v0.2.5/xterrafile_0.2.5_Darwin_x86_64.tar.gz"
  version "0.2.5"
  sha256 "fcdd4bf129d318d44836552fcf51a0e08be07e77c443a216939c87b6e0d58e41"

  def install
    bin.install "xterrafile"
  end
end
